---
- name: basic initialization playbook for rhel host 
  hosts: all
  tasks:
  - include_role:
      name: common-packages
  - include_role:
      name: aws_config
  - include_role:
      name: ddns

