---

- name: write out ddns.sh file
  template:
    src: ddns.sh.j2
    dest: /usr/local/bin/ddns.sh
    owner: root
    group: root
    mode: '0700'

- name: setup cron for ddns
  cron:
    name: "renew dynamic DNS IP"
    minute: "*/10"
    job: "/usr/local/bin/ddns.sh"
